/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as MesCommandesRouteImport } from './routes/mes-commandes'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const MesCommandesRoute = MesCommandesRouteImport.update({
  id: '/mes-commandes',
  path: '/mes-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/inscription': typeof InscriptionRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/mon-compte': typeof MonCompteRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/inscription': typeof InscriptionRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/mon-compte': typeof MonCompteRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/inscription': typeof InscriptionRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/mon-compte': typeof MonCompteRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/inscription'
    | '/mes-commandes'
    | '/mon-compte'
    | '/paiement'
    | '/panier'
    | '/produit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/inscription'
    | '/mes-commandes'
    | '/mon-compte'
    | '/paiement'
    | '/panier'
    | '/produit/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/inscription'
    | '/mes-commandes'
    | '/mon-compte'
    | '/paiement'
    | '/panier'
    | '/produit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CategoriesRoute: typeof CategoriesRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  InscriptionRoute: typeof InscriptionRoute
  MesCommandesRoute: typeof MesCommandesRoute
  MonCompteRoute: typeof MonCompteRoute
  PaiementRoute: typeof PaiementRoute
  PanierRoute: typeof PanierRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-commandes': {
      id: '/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof MesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CategoriesRoute: CategoriesRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  InscriptionRoute: InscriptionRoute,
  MesCommandesRoute: MesCommandesRoute,
  MonCompteRoute: MonCompteRoute,
  PaiementRoute: PaiementRoute,
  PanierRoute: PanierRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
